### ISSUE TITLE
Classpath libs separator is ":" (not ;) for *nix

### ISSUE THREAD

**Issue by gerbsen** [GeoKnow/TripleGeo#3]
java -cp "./lib/*;./build/jars/TripleGeo.jar" eu.geoknow.athenarc.triplegeo.ShpToRdf options.conf

fails

java -cp "./lib/*:./build/jars/TripleGeo.jar" eu.geoknow.athenarc.triplegeo.ShpToRdf options.conf

Change in readme file

**Comment by Naurah** [comment]
hi guyss.. i have been trying to run the tool but unsuccessfull.
I was stuck at extracting the shapefiles to Triple by using this command:
java -cp lib/*;bin/TripleGeo.jar eu.geoknow.athenarc.triplegeo.ShpToRdf options.conf.
I got an error that said could not find or load main class eu.geoknow.athenarc.triplegeo.ShpToRdf..

How can i fix it?

Many thanks in advance..

**Comment by KostasPatroumpas** [comment]
This error occurs when you make the call to the TripleGeo utility from a wrong directory. When invoking the following specific command:
java -cp lib/*;bin/TripleGeo.jar eu.geoknow.athenarc.triplegeo.ShpToRdf options.conf
please make sure: (i) that the required paths to .jar files in bin/ and /lib are correct relative to your current directory (ii) if you are in a Linux/Unix system, replace the ';' separator in classpath with ':' and (iii) configuration file 'options.conf' is at the same directory from where you make the call to executable (otherwise specify its correct path).
Please take a look at the steps in https://github.com/GeoKnow/TripleGeo/#1b-use-prepackaged-jars for more details. Many thanks for your feedback!
